version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  otel-collector:
    image: otel/opentelemetry-collector:0.72.0
    ports:
      - "4317:4317" # OTLP gRPC port
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
  jaeger:
    image: jaegertracing/all-in-one:1.36
    ports:
      - "5775:5775"
      - "5778:5778"
      - "14250:14250" # gRPC
      - "14268:14268" # HTTP
      - "16686:16686" # Jaeger UI

